urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'sweeper'

urlpatterns = [
	path('', views.index, name='index'),
	path('about/', views.about, name='about'),
	path('timetable/', views.timetable, name='timetable'),
	path('timetable/add/', views.add, name='add'),
	path('timetable/remove/', views.remove, name='remove'),
	path('group/<int:groupID>/', views.group, name='group'),
	path('group/<int:groupID>/add/', views.groupAdd, name='groupAdd'),
	path('group/<int:groupID>/remove/', views.groupRemove, name='groupRemove'),
	path('group/<int:groupID>/meeting/at/', views.atMeeting, name='atMeeting'),
	path('group/<int:groupID>/membership/', views.groupMembership, name='groupMembership'),
	path('group/<int:groupID>/admin/user/', views.adminUser, name='adminUser'),
	path('group/create/', views.createGroup, name='createGroup'),
	path('group/invitation/', views.invitation, name='invitation'),
]

templates/sweeper/about.html
{% extends "sweeper/base.html" %}

{% block title %}Home{% endblock %}

{% block head %}

<script>

	gGroupCreateUrl = "{% url 'sweeper:createGroup' %}";
	gInvitationUrl = "{% url 'sweeper:invitation' %}";

</script>

{% endblock %}

{% block content %}

<div class="row">
	<div class="col-sm-12 unpaddedCol">
		<div class="card bg-light">
			<h1 class="card-header">About Time Sweeper</h1>
			<div class="card-body">
				<h5 class="card-title">What is Time Sweeper?</h5>
				<p class="card-text">
					Time Sweeper is a web app that allows you to set regular weekly meetings with a group of people. The app takes into account each person's personal timetable to display all the possible intervals where the whole group is free to meet.
				</p>
				<h5 class="card-title">How does it do that?</h5>
				<p class="card-text">
					The app takes all the personal timetable intervals (called activities) from everyone in the group AND all the meetings accepted by users in this group (across their own groups) and merges them into a new set of intervals which are then displayed. This ensures your own timetable is as private as possible.
				</p>
				<h5 class="card-title">How do I use it?</h5>
				<p class="card-text">
					Once registered, you can edit your own timetable by drawing new events or editing/resizing/moving already created ones, and giving them a title. You can also create groups, or accept invitations to them.
				</p>
				<p class="card-text">
					There are 4 roles in groups:
					<ul>
						<li class="text-danger">Founder - can't be kicked and can give admin permissions, invite and kick people and edit admin-locked meetings. There's only one per group.</li>
						<li class="text-primary">Admin - can invite and kick people and edit admin-locked meetings.</li>
						<li class="text-secondary">Regular - can only edit regular meetings.</li>
						<li class="text-success">Invitee - hasn't accepted the group invitation yet, can only see the group's timetable once he has acepted (and vice versa).</li>
					</ul>
				</p>
				<p class="card-text">
					Once in a group, you can create and edit meetings, adding a title, location and other notes. You can also declare whether you're going to a meeting or not. If you are, the meeting changes color, shows up on your personal timetable and home page, and is added to the "blocked" time intervals on your other groups' timetables - this prevents you from accepting conflicting meetings.
				</p>
				<h5 class="card-title">Why was it made?</h5>
				<p class="card-text">
					This project was the subject of my third year dissertation for my CS BSc at the University of Liverpool. The original idea came to me due to having a hard time booking weekly practices with my band, since we did not know each other's weekly schedules.
				</p>
			</div>
		</div>

		<br>
		<hr class="d-sm-none">
	</div>
</div>

{% endblock %}

templates/sweeper/activityModal.html
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="modalTitle">Edit activity</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<div class="form-group row">
					<label for="evtTitle" class="col-sm-2 col-form-label">Title</label>
					<div class="col-sm-10">
						<input type="text" class="form-control" id="evtTitle" value="">
					</div>
				</div>
				<div id="hiddenModal">
					<div class="form-group row">
						<div class="col-sm-12">
							<button type="button" class="btn btn-danger btn-block" id="evtDelete" data-dismiss="modal" onclick="deleteEvt()">Delete activity</button>
						</div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				<button type="button" class="btn btn-primary" data-dismiss="modal" onclick="editActivity()">Save changes</button>
			</div>
		</div>
	</div>
</div>

templates/sweeper/adminUserModal.html
<div class="modal fade" id="userAdminModal" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="userAdminModalTitle">User admin</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<div class="form-group row">
					<div class="col-sm-12">
						<button type="button" class="btn btn-danger btn-block" id="kick" data-dismiss="modal" onclick="kick()">Kick user</button>
					</div>
				</div>
				<div id="hiddenAdminModal">
					<div class="form-group row">
						<div class="col-sm-12">
							<div class="btn-group btn-group-toggle btn-block" data-toggle="buttons">
								<label class="btn btn-secondary">
									<input type="radio" name="options" id="giveAdmin" autocomplete="off" onclick="giveAdmin()"> Admin
								</label>
								<label class="btn btn-secondary active">
									<input type="radio" name="options" id="removeAdmin" autocomplete="off" checked onclick="removeAdmin()"> Regular
								</label>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				<button type="button" class="btn btn-primary" data-dismiss="modal" onclick="editMeeting()">Save changes</button>
			</div>
		</div>
	</div>
</div>

templates/sweeper/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{% block title %}Time Sweeper{% endblock %}</title>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

	{% load static %}

	<script src="{% static 'sweeper/utils.js' %}"></script>
	<link rel="stylesheet" href="{% static 'sweeper/style.css' %}">

	{% block head %}{% endblock %}

</head>
<body>

<div class="jumbotron text-center" style="margin-bottom:0;background-image: url({% static 'sweeper/water.png' %})">
	<h1>Time Sweeper</h1>
</div>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
	<a class="navbar-brand" href="{% url 'sweeper:index' %}">Home</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="collapsibleNavbar">
		<ul class="navbar-nav">
			{% if user.is_authenticated %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'sweeper:timetable' %}">Timetable</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'main:logout' %}">Logout</a>
			</li>
			{% endif %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'sweeper:about' %}">About</a>
			</li>
		</ul>
	</div>  
</nav>

<div class="container" style="margin-top:30px">
{% block content %}{% endblock %}
</div>

<footer class="footer">
	<div class="jumbotron text-center" style="margin-bottom:0">
		<p>Time Sweeper 2020 - by luis</p>
	</div>
</footer>

</body>
</html>

templates/sweeper/eventList.html
<div class="card bg-light">
	<h1 class="card-header">Meeting list</h1>
	<div class="card-body">
		{% for meeting in meetings %}
			<div class="card mb-3">
				<div class="card-body">
					<h5 class="card-title">{{ meeting.group.name }}</h5>
					<h6 class="card-subtitle mb-2 text-muted">{{ meeting.obj.title }}</h6>
					<p class="card-text">
						{{ meeting.timeFormat.dateA }} - {{ meeting.timeFormat.dateB }}
						<br>
						{{ meeting.timeFormat.timeA }} - {{ meeting.timeFormat.timeB }}
					</p>
					<div class="card-subtitle mb-2">
						<h5>Users going</h5>
					</div>
					<div class="container border rounded" id="goingContainer">
						<div class="row text-center" id="goingRow">
							{% for groupMember in meeting.goingMembers %}
								<div class="col-sm-4 my-auto">
									<h6>{{ groupMember.username }}</h6>
								</div>
							{% endfor %}
						</div>
					</div>
					<a href="{% url 'sweeper:group' meeting.group.id %}" class="card-link">View group</a>
				</div>
			</div>
		{% empty %}
			<h5>No meetings yet!</h5>
		{% endfor %}
	</div>
</div>

templates/sweeper/group.html
{% extends "sweeper/base.html" %}

{% block title %}{{ group.name }}{% endblock %}

{% block head %}

{% load static %}

<link href="{% static 'sweeper/calendar/core/main.css' %}" rel='stylesheet' />
<link href="{% static 'sweeper/calendar/daygrid/main.css' %}" rel='stylesheet' />
<link href="{% static 'sweeper/calendar/timegrid/main.css' %}" rel='stylesheet' />
<link href="{% static 'sweeper/calendar/list/main.css' %}" rel='stylesheet' />
<script src="{% static 'sweeper/calendar/core/main.js' %}"></script>
<script src="{% static 'sweeper/calendar/interaction/main.js' %}"></script>
<script src="{% static 'sweeper/calendar/daygrid/main.js' %}"></script>
<script src="{% static 'sweeper/calendar/timegrid/main.js' %}"></script>
<script src="{% static 'sweeper/calendar/list/main.js' %}"></script>

<script>

	var evts = [

		{% for interval in blockedDates %}
			{
				title: '',
				start: '{{ interval.start }}',
				end: '{{ interval.end }}',
				editable: false,
				evType: 'static',
				rendering: 'background',
				color: 'blue'
			},
		{% endfor %}

		{% for interval in meetingDates %}
			{
				title: '{{ interval.title }}',
				start: '{{ interval.start }}',
				end: '{{ interval.end }}',
				color: '{{ interval.color }}',
				going: '{{ interval.going }}',
				location: '{{ interval.location }}',
				notes: '{{ interval.notes }}',
				lock: '{{ interval.lock }}',
				goingMembers: {{ interval.goingMembers|safe }}
			},
		{% endfor %}

	];


	gAddUrl = "{% url 'sweeper:groupAdd' groupID %}";
	gRemUrl = "{% url 'sweeper:groupRemove' groupID %}";
	gAtMeetingUrl = "{% url 'sweeper:atMeeting' groupID %}";
	gMembershipUrl = "{% url 'sweeper:groupMembership' groupID %}";
	gUserAdminUrl = "{% url 'sweeper:adminUser' groupID %}";

	gIsAdmin = "{{ usergroup.admin }}";


	buildCalender(GROUP_TABLE, "{{ date }}", evts);

</script>

{% endblock %}


{% block content %}

{% include "sweeper/meetingModal.html" %}
{% include "sweeper/leaveGroupModal.html" %}
{% include "sweeper/adminUserModal.html" %}


<div class="form-group row border rounded">
	<div class="col-sm-4 my-auto text-center">
		<h1>{{ group.name }}{% if group.founder == user %} (founder){% elif usergroup.admin %} (admin){% endif %}</h1>
	</div>

	{% if usergroup.admin %}
		<div class="col-sm-4 my-auto">
			<input type="text" class="form-control" id="addUsername" value="" placeholder="Username">
		</div>
		
		<div class="col-sm-2 my-auto">
			<button type="button" class="btn btn-primary btn-block" onclick="addUsername()">Invite</button>
		</div>
	{% else %}
		<div class="col-sm-6 my-auto">
		</div>
	{% endif %}

	<div class="col-sm-2 my-auto">
		<button type="button" class="btn btn-warning btn-block" onclick="openLeaveModal()">Leave group</button>
	</div>
</div>

<div class="row">
	<div class="col-sm-12 unpaddedCol">
		<div class="card bg-light">
			<div class="card-header">
				<div class="container">
					<div class="row">
						<div class="col my-auto text-center">
							<h3>Member list</h3>
						</div>
						<div class="col-sm-auto my-auto text-center">
							<h6>
								<span class="badge badge-pill badge-danger">Founder</span>
								<span class="badge badge-pill badge-primary">Admin</span>
								<span class="badge badge-pill badge-secondary">Regular</span>
								<span class="badge badge-pill badge-success">Invited</span>
							</h6>
						</div>
					</div>
				</div>
			</div>

			<div class="card-body text-center">
				{% include "sweeper/memberList.html" %}
			</div>
		</div>
	</div>
</div>

<br>

<div class="row border rounded">
	<div class="col-sm-12">
		<br>
		<div id='calendar'></div>
		<br>
	</div>
</div>

{% endblock %}

templates/sweeper/groupList.html
<div class="card mb-3">
	<h2 class="card-header">Groups</h2>
	<div class="card-body">
		<p class="card-text">
			<ul class="nav nav-pills flex-column">
			{% for group in groups %}
				<li class="nav-item">
					<a class="nav-link btn btn-primary marginBtn" href="{% url 'sweeper:group' group.id %}"><h3>{{ group.name }}</h3></a>
				</li>
			{% empty %}
				<li>
					<h5>No groups yet!</h5>
				</li>
			{% endfor %}
			</ul>
		</p>
	</div>
</div>

<div class="card mb-3">
	<h2 class="card-header">Invites</h2>
	<div class="card-body">
		<p class="card-text">
			<ul class="nav nav-pills flex-column">
			{% for invite in invites %}
				<li class="nav-item">
					<div class="btn-group btn-block">
						<button type="button" class="btn btn-success btn-block marginBtn" onclick="acceptGroup({{ invite.id }})"><h3>{{ invite.name }}</h3></button>
						<button type="button" class="btn btn-danger marginBtn" onclick="denyGroup({{ invite.id }})"><h3>X</h3></button></h3></button>
					</div>
				</li>
			{% empty %}
				<li>
					<h5>No invites yet!</h5>
				</li>
			{% endfor %}
			</ul>
		</p>
	</div>
</div>

templates/sweeper/index.html
{% extends "sweeper/base.html" %}

{% block title %}Home{% endblock %}

{% block head %}

<script>

	gGroupCreateUrl = "{% url 'sweeper:createGroup' %}";
	gInvitationUrl = "{% url 'sweeper:invitation' %}";

</script>

{% endblock %}

{% block content %}

<div class="row">
	<div class="col-sm-4">
		<div class="card bg-light">
			<h1 class="card-header">Hi, {{ user.get_username }}</h1>
			<div class="card-body">
				{% include "sweeper/groupList.html" %}

				<div class="card mb-3">
					<h2 class="card-header">Create group</h2>

					<div class="card-body">
						<div class="form-group">
							<input type="text" class="form-control" id="createGroupName" value="" placeholder="Group name">
						</div>

						<div class="form-group">
							<button type="button" class="btn btn-primary btn-block" onclick="createGroup()">Create</button>
						</div>
					</div>
				</div>
			</div>
		</div>

		<br>
		<hr class="d-sm-none">
	</div>
	<div class="col-sm-8">
		{% include "sweeper/eventList.html" %}
		<br>
		<hr class="d-sm-none">
	</div>
</div>

{% endblock %}

templates/sweeper/leaveGroupModal.html
<div class="modal fade" id="modalLeave" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="modalLeaveTitle">Leave group?</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<div class="form-group row">
					<div class="col-sm-12">
						<button type="button" class="btn btn-danger btn-block" id="leaveGroup" data-dismiss="modal" onclick="leaveGroup()">Leave</button>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>

templates/sweeper/meetingModal.html
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="modalTitle">Edit meeting</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<div class="form-group row">
					<label for="evtTitle" class="col-sm-1 col-form-label">Title</label>
					<div class="col-sm-11">
						<input type="text" class="form-control" id="evtTitle" value="">
					</div>
				</div>
				<div class="form-group row">
					<label for="evtLocation" class="col-sm-2 col-form-label">Location</label>
					<div class="col-sm-10">
						<input type="text" class="form-control" id="evtLocation" value="">
					</div>
				</div>
				<div class="form-group row">
					<div class="col-sm-12">
						<textarea class="form-control" rows="4" id="evtNotes" placeholder="Meeting notes" value=""></textarea>
					</div>
				</div>
				<div class="form-group row{% if not usergroup.admin %} d-none{% endif %}">
					<div class="col-sm-12">
						<div class="btn-group btn-group-toggle btn-block" data-toggle="buttons">
							<label class="btn btn-secondary">
								<input type="radio" name="lockRadio" id="locked" autocomplete="off" value="true"> Locked
							</label>
							<label class="btn btn-secondary active">
								<input type="radio" name="lockRadio" id="unlocked" autocomplete="off" value="false" checked> Unlocked
							</label>
						</div>
					</div>
				</div>
				<div id="hiddenModal">
					<div class="form-group row">
						<div class="col-sm-12">
							<div class="btn-group btn-group-toggle btn-block" data-toggle="buttons">
								<label class="btn btn-secondary">
									<input type="radio" name="options" id="going" autocomplete="off" onclick="evtGoing()"> Going
								</label>
								<label class="btn btn-secondary active">
									<input type="radio" name="options" id="notGoing" autocomplete="off" checked onclick="evtNotGoing()"> Not going
								</label>
							</div>
						</div>
					</div>
					<div class="form-group row">
						<div class="col-sm-12">
							<button type="button" class="btn btn-danger btn-block" id="evtDelete" data-dismiss="modal" onclick="deleteEvt()">Delete meeting</button>
						</div>
					</div>
					<br>
					<div class="row text-center">
						<div class="col-sm-12">
							<h4>Users going</h4>
						</div>
					</div>
					<div class="container border rounded" id="goingContainer">
						<div class="row text-center" id="goingRow">
						</div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				<button type="button" id="modalSave" class="btn btn-primary" data-dismiss="modal" onclick="editMeeting()">Save changes</button>
			</div>
		</div>
	</div>
</div>

templates/sweeper/memberList.html
<div class="container" id="memberContainer">
	<div class="row">
		{% for member in members %}
			<div class="col-sm-4 col-md-3 my-auto">
				{% if usergroup.admin and group.founder != member.user and user != member.user %}
					<button type="button" class="marginBtn btn btn-block {% if group.founder == member.user %}btn-danger{% elif not member.accepted %}btn-success{% elif member.admin %}btn-primary{% else %}btn-secondary{% endif %}" onclick="openAdminUserModal(
					{{ user.id }},
					{{ group.founder.id }},
					{{ member.user.id }},
					'{{ member.admin }}',
					'{{ member.accepted }}'
					)">
						<h4>{{ member.user.username }}</h4>
					</button>	
				{% else %}
					<h4 class="{% if group.founder == member.user %}text-danger{% elif not member.accepted %}text-success{% elif member.admin %}text-primary{% else %}text-secondary{% endif %}">
						{{ member.user.username }}
					</h4>
				{% endif %}
			</div>
		{% empty %}
			<div class="col-12">
				<h5>No members yet!</h5>
			</div>
		{% endfor %}
	</div>
</div>

templates/sweeper/timetable.html
{% extends "sweeper/base.html" %}

{% block title %}Timetable{% endblock %}

{% block head %}

{% load static %}

<link href="{% static 'sweeper/calendar/core/main.css' %}" rel='stylesheet' />
<link href="{% static 'sweeper/calendar/daygrid/main.css' %}" rel='stylesheet' />
<link href="{% static 'sweeper/calendar/timegrid/main.css' %}" rel='stylesheet' />
<link href="{% static 'sweeper/calendar/list/main.css' %}" rel='stylesheet' />
<script src="{% static 'sweeper/calendar/core/main.js' %}"></script>
<script src="{% static 'sweeper/calendar/interaction/main.js' %}"></script>
<script src="{% static 'sweeper/calendar/daygrid/main.js' %}"></script>
<script src="{% static 'sweeper/calendar/timegrid/main.js' %}"></script>
<script src="{% static 'sweeper/calendar/list/main.js' %}"></script>

<script>

	var evts = [

		{% for interval in meetingDates %}
			{
				title: '{{ interval.group }}\n\n{{ interval.title }}',
				start: '{{ interval.start }}',
				end: '{{ interval.end }}',
				editable: false,
				evType: 'redirect',
				redirect: '{{ interval.redirect }}',
				color: 'lightgreen'
			},
		{% endfor %}

		{% for interval in activityDates %}
			{
				title: '{{ interval.title }}',
				start: '{{ interval.start }}',
				end: '{{ interval.end }}'
			},
		{% endfor %}

	];


	gAddUrl = "{% url 'sweeper:add' %}";
	gRemUrl = "{% url 'sweeper:remove' %}";


	buildCalender(USER_TABLE, "{{ date }}", evts);

</script>

{% endblock %}


{% block content %}

{% include "sweeper/activityModal.html" %}

<div class="form-group row border rounded">
	<div class="col-sm-12 my-auto text-center">
		<h1>Edit your timetable</h1>
	</div>
</div>

<br>

<div class="row border rounded">
	<div class="col-sm-12">
		<br>
		<div id='calendar'></div>
		<br>
	</div>
</div>

{% endblock %}